### ISSUE TITLE
Container build dependency on accelerators (requires TPU VM)

### ISSUE THREAD

**Issue by ultrons** [google/maxdiffusion#32]
https://github.com/google/maxdiffusion/blob/inf_mlperf/docker/sdxl_inference/model_loader.py
is executed the dockerfile and requires the build to be executed on TPU VM.
Can we replace this with xAOT to eliminate this dependency?

**Comment by entrpn** [comment]
@ultrons it is not a requirement to build Docker on a TPU VM. When this gets loaded, it uses cpu, see (this line)[https://github.com/google/maxdiffusion/blob/inf_mlperf/docker/sdxl_inference/dockerfile/Dockerfile#L30].

**Comment by entrpn** [comment]
@ultrons does this answer your question?
