### ISSUE TITLE
latents concatenation in training flops calculation

### ISSUE THREAD

**Issue by mailvijayasingh** [google/maxdiffusion#65]
https://github.com/google/maxdiffusion/blob/main/src/maxdiffusion/max_utils.py#L452
While training, is it needed to concat latents? 

Should it be concatenated only during inference and not during training?

**Comment by entrpn** [comment]
This is still an issue. The aot cost_analysis function does not seem to be deterministic and provide a good estimate, specially with the splash attention kernel. Needs more investigation. Reopening.

**Comment by entrpn** [comment]
Moving to per layer calculations, tested with sd 2 base and sdxl. #79 should now report more accurate flop calculations.
